spring:
  application:
    name: trip-planner-gateway

  output:
    ansi:
      enabled: ALWAYS

  cloud:
    gateway:
      routes:
        - id: trip-planner-user-service
          uri: lb://TRIP-PLANNER-USER-SERVICE
          predicates:
            - Path=/auth/**,/users/**
          filters:
            - PrefixPath=/api
            - AuthenticationFilter

        - id: trip-planner-trip-service
          uri: lb://TRIP-PLANNER-TRIP-SERVICE
          predicates:
            - Path=/trips/**
          filters:
            - PrefixPath=/api
            - AuthenticationFilter

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG

reactor:
  netty:
    http:
      client: DEBUG
